### ISSUE TITLE
[Info] Installing recommended packages -> Failure to complete

### ISSUE THREAD

**Issue by Torbuntu** [nikhiljha/pp-fedora-sdsetup#122]
Not entirely sure what is happening, but when installing recommended packages there is a python error:
```
[Info] Installing recommended packages...
Traceback (most recent call last):
  File "/usr/bin/dnf", line 62, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 201, in user_main
    errcode = main(args)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 67, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 106, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 130, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 176, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.10/site-packages/dnf/cli/cli.py", line 238, in do_transaction
    self.gpgsigcheck(install_pkgs)
  File "/usr/lib/python3.10/site-packages/dnf/cli/cli.py", line 294, in gpgsigcheck
    self._get_key_for_package(po, fn)
  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 2447, in _get_key_for_package
    keys = dnf.crypto.retrieve(keyurl, repo)
  File "/usr/lib/python3.10/site-packages/dnf/crypto.py", line 186, in retrieve
    keyinfos = rawkey2infos(handle)
  File "/usr/lib/python3.10/site-packages/dnf/crypto.py", line 165, in rawkey2infos
    with pubring_dir(pb_dir), Context() as ctx:
  File "/usr/lib64/python3.10/site-packages/gpg/core.py", line 225, in __init__
    self.protocol = protocol
  File "/usr/lib64/python3.10/site-packages/gpg/core.py", line 174, in __setattr__
    super(GpgmeWrapper, self).__setattr__(key, value)
  File "/usr/lib64/python3.10/site-packages/gpg/core.py", line 1134, in protocol
    errorcheck(gpgme.gpgme_engine_check_version(value))
  File "/usr/lib64/python3.10/site-packages/gpg/errors.py", line 129, in errorcheck
    raise GPGMEError(retval, extradata)
gpg.errors.GPGMEError: GPGME: Invalid crypto engine
```

I am unable to generate new images due to this.

**Comment by alh61** [comment]
I don't know what it is either - but it is COPR that has this problem.Using --nogpgcheck works around the problem.
It only happens for files, that gets installed from COPR.
